"""create lead history table

Revision ID: 3dd650dd94f9
Revises: 6f36965481df
Create Date: 2026-07-30 10:41:33.262501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd650dd94f9'
down_revision: Union[str, Sequence[str], None] = '6f36965481df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_history',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_history_action'), 'lead_history', ['action'], unique=False)
    op.create_index(op.f('ix_lead_history_company_id'), 'lead_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_lead_history_lead_id'), 'lead_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_history_user_id'), 'lead_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_history_user_id'), table_name='lead_history')
    op.drop_index(op.f('ix_lead_history_lead_id'), table_name='lead_history')
    op.drop_index(op.f('ix_lead_history_company_id'), table_name='lead_history')
    op.drop_index(op.f('ix_lead_history_action'), table_name='lead_history')
    op.drop_table('lead_history')
    # ### end Alembic commands ###
