"""create lead tags table

Revision ID: 6f36965481df
Revises: 9d7282439816
Create Date: 2026-07-30 10:19:55.099617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f36965481df'
down_revision: Union[str, Sequence[str], None] = '9d7282439816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_tags',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'tag_id', name='uq_lead_tags_lead_id_tag_id')
    )
    op.create_index(op.f('ix_lead_tags_lead_id'), 'lead_tags', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_tags_tag_id'), 'lead_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_tags_tag_id'), table_name='lead_tags')
    op.drop_index(op.f('ix_lead_tags_lead_id'), table_name='lead_tags')
    op.drop_table('lead_tags')
    # ### end Alembic commands ###
