"""add service to appointments

Revision ID: 71975bb476c9
Revises: d4552e1ff98e
Create Date: 2026-07-30 02:08:38.634645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71975bb476c9'
down_revision: Union[str, Sequence[str], None] = 'd4552e1ff98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_foreign_key('appointments_service_id_fkey', 'appointments', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_service_id_fkey', 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_column('appointments', 'service_id')
    # ### end Alembic commands ###
